--------------------------------------------------------------------------------
-- File: config/settings-updates.lua
-- Purpose: Adjusts settings when mods are added/removed (placeholder).
--------------------------------------------------------------------------------
